templates/website/routes.py
from flask import Blueprint,render_template,redirect,request,session
import requests
from templates.interceptor import authInterceptor,protected_guard
import json
from config import apiUrl
from flask import flash
import base64
from datetime import datetime
from templates.authentication.forms.loginform import ApplyJob,UserProfile,SendMessage,ContactUs,ReviewForm
from werkzeug.utils import secure_filename
import os
website_blueprint = Blueprint('website_blueprint', __name__)
@website_blueprint.route('/')
def index():
    return redirect('/home')

@website_blueprint.route('/home')
def home():
    user =  session.get('user')
    user = json.loads(user) if user else None
    return render_template('website/views/home.html',user = user, segment='index')

@website_blueprint.route('/contact-us',methods = ['GET','POST'])
def contactUs():
    form = ContactUs()
    user =  session.get('user')
    user = json.loads(user) if user else None
    if(user and user['isBlocked']==1):
        form.name.data = user['name']
        form.email.data = user['email']
        form.name.render_kw = {'disabled': True}
        form.email.render_kw = {'disabled': True}
    if form.validate_on_submit():
        body = {
            "name":form.name.data,
            "email":form.email.data,
            "subject":form.subject.data,
            "comment":form.comment.data
        }
        resp = requests.post(
        apiUrl+'/contact/contact-us',
        json.dumps(body, indent = 4),
        headers = {
        "Content-Type": "application/json; charset=utf-8"
        })
        resp = json.loads(resp.text)
        form.process()
        if(resp['success']):
            flash('Message Send Successfully', 'success')
        else:
            flash('Error on sending message', 'error')
    return render_template('website/views/contact-us.html',user = user, segment='index',form=form)

@website_blueprint.route('/about-us')
def aboutUs():
    user =  session.get('user')
    user = json.loads(user) if user else None
    return render_template('website/views/about-us.html',user = user, segment='index')

@website_blueprint.route('/corporate-values')
def corporateValues():
    user =  session.get('user')
    user = json.loads(user) if user else None
    return render_template('website/views/corporate-values.html',user = user, segment='index')

@website_blueprint.route('/chat/<int:receiver_id>')
@protected_guard
@authInterceptor
def chat(access_token,receiver_id):
    user = json.loads(session.get('user'))
    userId = user['user_id']
    form = SendMessage()
    resp = requests.get(
            apiUrl+'/chat/get-all-user-chat/'+str(json.loads(session.get('user'))['user_id'])+'/'+str(receiver_id),
            headers = {
            "Content-Type": "application/json; charset=utf-8",
            "Authorization": "Bearer " + access_token
            })
    resp = json.loads(resp.text)
    data = resp['data'] if resp['success'] else []
    return render_template('website/views/chat-website.html',chats=data,userId=userId,user = user,receiver_id=receiver_id,form=form)

@website_blueprint.route('/job-detail/<int:event_id>')
@protected_guard
@authInterceptor
def jobDetail(access_token,event_id):
    user =  session.get('user')
    user = json.loads(user) if user else None
    resp = requests.get(
            apiUrl+'/events/get-all-event-by-id/'+str(event_id),
            headers = {
            "Content-Type": "application/json; charset=utf-8",
            "Authorization": "Bearer " + access_token
            })
    resp = json.loads(resp.text)
    eventInfo = resp['data'] if resp['success'] else None
    return render_template('website/views/job-detail.html',user = user, eventInfo = eventInfo, segment='index')

@website_blueprint.route('/user-profile',methods=["GET","POST"])
@authInterceptor
@protected_guard
def userProfile(access_token):
    user =  session.get('user')
    user = json.loads(user) if user else None
    form = UserProfile()
    if form.validate_on_submit():
        body = {
            "user_id":json.loads(session.get('user'))['user_id'],
            "name":form.name.data,
            "city":form.city.data,
            "country":form.country.data,
            "dob":form.dob.data.isoformat(),
            "about":form.about.data,
            "skills":form.skills.data
        }
        resp = requests.post(
        apiUrl+'/users/update-user-info',
        json.dumps(body, indent = 4),
        headers = {
        "Content-Type": "application/json; charset=utf-8",
        "Authorization": "Bearer " + access_token
        })
        resp = json.loads(resp.text)
        if(resp['success']):
            flash('Update Profile Successfully', 'success')
        else:
            flash('Error on updating profile', 'error')
  
    newResp = requests.get(
        apiUrl+'/users/user-info',
        headers = {
        "Content-Type": "application/json; charset=utf-8",
        "Authorization": "Bearer " + access_token
        })
    newResp = json.loads(newResp.text)
    userInfo = newResp['data'] if newResp['success'] else None
    form.name.data = userInfo['name']
    form.city.data = userInfo['city'] if userInfo['city'] else ''
    form.country.data = userInfo['city'] if userInfo['country'] else ''
    form.dob.data = datetime.strptime(userInfo['birthday'], '%Y-%m-%d').date() if userInfo['birthday'] else ''
    form.about.data = userInfo['about'] if userInfo['about'] else ''
    form.skills.data = userInfo['skills'] if userInfo['skills'] else ''
    return render_template('website/views/user-profile.html',user = user,form = form , userInfo=userInfo, segment='index',access_token=access_token)

@website_blueprint.route('/user-application')
@protected_guard
@authInterceptor
def userApplication(access_token):
    form = ReviewForm()
    user =  session.get('user')
    user = json.loads(user) if user else None
    resp = requests.get(
            apiUrl+'/events/view-user-application',
            headers = {
            "Content-Type": "application/json; charset=utf-8",
            "Authorization": "Bearer " + access_token
            })
    resp = json.loads(resp.text)
    data = resp['data'] if resp['success'] else []
    return render_template('website/views/user-application.html',form=form,user = user,data = data, segment='index')

@website_blueprint.route('/volunteer-tasks')
@protected_guard
@authInterceptor
def volunteerTasks(access_token):
    user =  session.get('user')
    user = json.loads(user) if user else None
    body = {
        "page":1,
        "limit":10
    }
    resp = requests.post(
            apiUrl+'/events/get-all-events',
            json.dumps(body, indent = 4),
            headers = {
            "Content-Type": "application/json; charset=utf-8",
            "Authorization": "Bearer " + access_token
            })
    resp = json.loads(resp.text)
    if(resp['success']):
        return render_template('website/views/volunteer-tasks.html',user = user,events=resp['data'],page="events")
    else:
        return render_template('website/views/volunteer-tasks.html',user = user,events=[],page="events")
@website_blueprint.route('/job-apply/<int:event_id>',methods=["GET","POST"])
@protected_guard
@authInterceptor
def jobApply(access_token,event_id):
    user =  session.get('user')
    user = json.loads(user) if user else None
    form =  ApplyJob()

    if form.validate_on_submit():
        file = dict(request.files)['cv']
        image_data = file.read()
        filename = secure_filename(file.filename)  # sanitize the filename
        filePath = 'assets/resume/event-'+str(event_id)+'/user-'+str(json.loads(session.get('user'))['user_id'])
        os.makedirs(filePath, exist_ok=True)
        file.seek(0)
        file.save(os.path.join(filePath, filename))
        # image_base64 = base64.b64encode(image_data).decode('utf-8')
        body = {
            "volunteer_id":json.loads(session.get('user'))['user_id'],
            "event_id":event_id,
            "cover_letter":form.cover_letter.data,
            "cv":filePath,
            "fileName":filename,
            "size": len(image_data)
        }
        resp = requests.post(
            apiUrl+'/events/apply-job-application',
            json.dumps(body, indent = 4),
            headers = {
            "Content-Type": "application/json; charset=utf-8",
            "Authorization": "Bearer " + access_token
            })
        resp = json.loads(resp.text)
        if(resp['success']):
            flash(resp['message'], 'success')
            # return render_template('admin/views/add-update-volunteer-task.html',form=form,resp=resp)
            return redirect('/volunteer-tasks')
        else:
            flash(resp['message'], 'error')
            return redirect('/job-apply/'+str(event_id))
    resp = requests.get(
            apiUrl+'/events/get-all-event-by-id/'+str(event_id),
            headers = {
            "Content-Type": "application/json; charset=utf-8",
            "Authorization": "Bearer " + access_token
            })
    resp = json.loads(resp.text)
    if(resp['success']):
        newResp = requests.get(
            apiUrl+'/users/user-info',
            headers = {
            "Content-Type": "application/json; charset=utf-8",
            "Authorization": "Bearer " + access_token
            })
        newResp = json.loads(newResp.text)
        userInfo = newResp['data'] if newResp['success'] else None
        return render_template('website/views/job-apply.html',user = user, form = form, events = resp['data'],userInfo=userInfo, segment='index')
    else: 
        return render_template('website/views/job-apply.html',user = user,  form = form, events = None,userInfo=None, segment='index')

@website_blueprint.route('/send-message/<int:reciever_id>',methods=['GET','POST'])
@protected_guard
@authInterceptor
def sendMessage(access_token,reciever_id):
    form = SendMessage()
    body = {
        "sender_id":json.loads(session.get('user'))['user_id'],

templates/website/views/chat-website.html
{% extends "website/layouts/base.html" %}
{% block content %}
<section class="relative table w-full py-36 bg-[url('../../assets/images/hero/bg.jpg')] bg-top bg-no-repeat bg-cover ">
    <div class="absolute inset-0 bg-emerald-900/90"></div>
    <div class="container">
        <div class="grid grid-cols-1 text-center mt-10">
            <h3 class="md:text-3xl text-2xl md:leading-snug tracking-wide leading-snug font-medium text-white">User Application</h3>

        </div><!--end grid-->
    </div><!--end container-->

</section><!--end section-->
<!-- < class="relative table w-full py-28 px-20 text-center"> -->
  <section class="flex flex-col items-center justify-center min-h-screen bg-gray-100 text-gray-800 p-28">

    <!-- Component Start -->
    <div style="background-color: rgb(16 185 129 / .9) !important" class="flex flex-col w-full max-w-xl bg-white shadow-xl rounded-t-lg overflow-hidden p-4">
      Chat
    </div>
    <div class="flex flex-col flex-grow w-full max-w-xl bg-white shadow-xl rounded-b-lg overflow-hidden">
      <div class="flex flex-col flex-grow h-0 p-4 overflow-auto">
        {% for chat in chats%}
        {% if chat.senderId != userId %}
        <div class="flex w-full mt-2 space-x-3 max-w-xs">
          
          <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-300"></div>
          <div>
            <div class="bg-gray-300 p-3 rounded-r-lg rounded-bl-lg">
              <p class="text-sm">{{chat.message}}</p>
            </div>
            <span class="text-xs text-gray-500 leading-none">{{chat.created_at}}</span>
          </div>
        </div>
        {% else %}
        <div class="flex w-full mt-2 space-x-3 max-w-xs ml-auto justify-end">
          <div>
            <div style="background-color: rgb(16 185 129 / .9) !important" class="text-white p-3 rounded-l-lg rounded-br-lg">
              <p class="text-sm">{{chat.message}}</p>
            </div>
            <span class="text-xs text-gray-500 leading-none">{{chat.created_at}}</span>
          </div>
          <div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-300"></div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
        <form action="/send-message/{{receiver_id}}" method="post" class="bg-gray-300 p-4 flex ">
          {{ form.hidden_tag() }}
    
          {{form.message(class="flex items-center h-10 rounded-l-lg px-3 text-sm content-start w-full" , placeholder="Type your message…")}}
        <button style="background-color: rgb(16 185 129 / .9) !important" class="py-2 px-6 text-white rounded-r-lg" type="submit">Send</button>
        
        </form>
    </div>
    <!-- Component End  -->
  
  <!-- </div> -->
</section>

{% endblock content %}
{% block javascripts %}
<script>
</script>
{% endblock javascripts %}

templates/website/views/job-apply.html
{% extends "website/layouts/base.html" %}
{% block content %}
<!-- Start Hero -->
<section class="relative table w-full py-36 bg-[url('../../assets/images/hero/bg.jpg')] bg-top bg-no-repeat bg-cover">
    <div class="absolute inset-0 bg-emerald-900/90"></div>
    <div class="container">
        <div class="grid grid-cols-1 text-center mt-10">
            <h3 class="md:text-3xl text-2xl md:leading-snug tracking-wide leading-snug font-medium text-white">Back-End Developer</h3>

        </div><!--end grid-->
    </div><!--end container-->
    
    <div class="absolute text-center z-10 bottom-5 right-0 left-0 mx-3">
        <ul class="breadcrumb tracking-[0.5px] breadcrumb-light mb-0 inline-block">
           <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white/50 hover:text-white"><a href="index.html">Jobstack</a></li>
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white" aria-current="page">Job apply form</li>
        </ul>
    </div>
</section><!--end section-->
<div class="relative">
    <div class="shape absolute right-0 sm:-bottom-px -bottom-[2px] left-0 overflow-hidden z-1 text-white dark:text-slate-900">
        <svg class="w-full h-auto" viewbox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>
<!-- End Hero -->

<!-- Start -->
<section class="relative bg-slate-50 dark:bg-slate-800 lg:py-24 py-16">
    <div class="container">
        <div class="md:flex justify-center">
            <div class="lg:w-2/4 md:w-2/3">
                <div class="p-6 bg-white dark:bg-slate-900 shadow dark:shadow-gray-700 rounded-md">
                    <form class="text-left" action="/job-apply/{{events.id}}" method="POST" enctype="multipart/form-data">
                        {{ form.hidden_tag() }}
                        <div class="grid grid-cols-1">
                            <div class="mb-4 ltr:text-left rtl:text-right">
                                <label for="JobType" class="font-semibold">Job:</label>
                                <input id="JobType" disabled type="text" class="form-input border border-slate-100 dark:border-slate-800 mt-1" placeholder="Job Type" value="{{events.title}}">
                            </div>

                            <div class="mb-4 ltr:text-left rtl:text-right">
                                <label class="font-semibold" for="RegisterName">Your Name:</label>
                                <input id="RegisterName" disabled type="text" class="form-input border border-slate-100 dark:border-slate-800 mt-1" placeholder="Harry" value="{{userInfo.name}}">
                            </div>

                            <div class="mb-4 ltr:text-left rtl:text-right">
                                <label class="font-semibold" for="LoginEmail">Email Address:</label>
                                <input id="LoginEmail" value="{{userInfo.email}}" disabled type="email" class="form-input border border-slate-100 dark:border-slate-800 mt-1" placeholder="name@example.com">
                            </div>

                            <div class="mb-4 ltr:text-left rtl:text-right">
                                <label class="font-semibold" for="PhoneNo">Phone No.:</label>
                                <input id="PhoneNo" value="{{userInfo.phone_number}}" disabled type="number" class="form-input border border-slate-100 dark:border-slate-800 mt-1" placeholder="+458 854-8965">
                            </div>

                            <div class="mb-4 ltr:text-left rtl:text-right">
                                <label for="statename" class="font-semibold">Location:</label>
                                <input id="statename"value="{{userInfo.city+''+userInfo.country if userInfo.country else '' }}" disabled type="text" class="form-input border border-slate-100 dark:border-slate-800 mt-1" placeholder="Harry">
                            </div>

                            <div class="mb-2 ltr:text-left rtl:text-right">
                                <label for="comments" class="font-semibold">Coverting Letter:</label>
                                {{ form.cover_letter( class="form-input border border-slate-100 dark:border-slate-800 mt-1 textarea", placeholder="Message :") }}
                                <!-- <textarea name="comments" id="comments" class="form-input border border-slate-100 dark:border-slate-800 mt-1 textarea" placeholder="Message :"></textarea> -->
                            </div>

                            <div class="mb-4 ltr:text-left rtl:text-right">
                                <label class="font-semibold" for="multiple_files">Upload Resume:</label>
                                {{ form.cv(accept="application/pdf",class="relative form-input border border-slate-100 dark:border-slate-800 file:h-10 file:-mx-3 file:-my-2 file:cursor-pointer file:rounded-none file:border-0 file:px-3 file:text-neutral-700 bg-clip-padding px-3 py-1.5 file:ltr:mr-3 file:rtl:ml-3 mt-1", id="multiple_files", type="file") }}
                                <!-- <input class="relative form-input border border-slate-100 dark:border-slate-800 file:h-10 file:-mx-3 file:-my-2 file:cursor-pointer file:rounded-none file:border-0 file:px-3 file:text-neutral-700 bg-clip-padding px-3 py-1.5 file:ltr:mr-3 file:rtl:ml-3 mt-1" id="multiple_files" type="file"> -->
                            </div>

                            <div>
                                <button type="submit" id="submit" name="send" class="btn rounded-md bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white">Send</button>
                            </div>
                        </div>
                    </form><!--end form-->
                </div>
            </div>
        </div><!--end flex-->
    </div><!--end container-->
</section><!--end section-->
<!-- End -->
{% endblock content %}

templates/website/views/job-detail.html
{% extends "website/layouts/base.html" %}
{% block content %}
<section class="relative table w-full py-36 bg-[url('../../assets/images/hero/bg.jpg')] bg-top bg-no-repeat bg-cover">
    <div class="absolute inset-0 bg-emerald-900/90"></div>
    <div class="container">
        <div class="grid grid-cols-1 text-center mt-10">
            <h3 class="md:text-3xl text-2xl md:leading-snug tracking-wide leading-snug font-medium text-white">{{eventInfo.title}}</h3>

        </div><!--end grid-->
    </div><!--end container-->
    
    <!-- <div class="absolute text-center z-10 bottom-5 right-0 left-0 mx-3">
        <ul class="breadcrumb tracking-[0.5px] breadcrumb-light mb-0 inline-block">
           <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white/50 hover:text-white"><a href="index.html">Job Detail</a></li>
            <li class="inline breadcrumb-item text-[15px] font-semibold duration-500 ease-in-out text-white" aria-current="page">Job Detail</li>
        </ul>
    </div> -->
</section><!--end section-->
<div class="relative">
    <div class="shape absolute right-0 sm:-bottom-px -bottom-[2px] left-0 overflow-hidden z-1 text-white dark:text-slate-900">
        <svg class="w-full h-auto" viewbox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>
<section class="bg-slate-50 dark:bg-slate-800 md:py-24 py-16">
    <div class="container mt-10">
        <div class="grid md:grid-cols-12 grid-cols-1 gap-[30px]">
            <div class="lg:col-span-8 md:col-span-6">
                <div class="md:flex items-center p-6 shadow dark:shadow-gray-700 rounded-md bg-white dark:bg-slate-900">
                    <img src="data:image/*;base64,{{eventInfo['image']}}" class="rounded-full h-28 w-28 p-4 bg-white dark:bg-slate-900 shadow dark:shadow-gray-700" alt="">

                    <div class="md:ltr:ml-4 md:rtl:mr-4 md:mt-0 mt-6">
                        <h5 class="text-xl font-semibold">{{eventInfo.title}}</h5>
                        <div class="mt-2">
                            <span class="text-slate-400 font-medium ltr:mr-2 rtl:ml-2 inline-block"><i class="uil uil-building text-[18px] text-emerald-600 ltr:mr-1 rtl:ml-1"></i> {{eventInfo.organization_name}}</span>
                            <span class="text-slate-400 font-medium ltr:mr-2 rtl:ml-2 inline-block"><i class="uil uil-map-marker text-[18px] text-emerald-600 ltr:mr-1 rtl:ml-1"></i> {{eventInfo.location}}</span>
                            <span class="text-slate-400 font-medium ltr:mr-2 rtl:ml-2 inline-block"><i class="uil uil-link text-[18px] text-emerald-600 ltr:mr-1 rtl:ml-1"></i> {%if eventInfo.website %}<a href="{{eventInfo.website}}" target="_blank">{{eventInfo.website}}</a> {%else%}No link Found {%endif%}</span>
                        </div>
                    </div>
                </div>

                <h5 class="text-lg font-semibold mt-6">Job Description:</h5>

                <p class="text-slate-400 mt-4">{{eventInfo.description}}</p>
                

                <!-- <h5 class="text-lg font-semibold mt-6">Required Experience, Skills and Qualifications: </h5>
                <p class="text-slate-400 mt-4">It sometimes makes sense to select texts containing the various letters and symbols specific to the output language.</p>
                <ul class="list-none">
                    <li class="text-slate-400 mt-2"><i class="uil uil-arrow-right text-emerald-600 ltr:mr-1 rtl:ml-1"></i>Proven experience as a .NET Developer or Application Developer</li>
                    <li class="text-slate-400 mt-2"><i class="uil uil-arrow-right text-emerald-600 ltr:mr-1 rtl:ml-1"></i>good understanding of SQL and Relational Databases, specifically Microsoft SQL Server.</li>
                    <li class="text-slate-400 mt-2"><i class="uil uil-arrow-right text-emerald-600 ltr:mr-1 rtl:ml-1"></i>Experience designing, developing and creating RESTful web services and APIs</li>
                    <li class="text-slate-400 mt-2"><i class="uil uil-arrow-right text-emerald-600 ltr:mr-1 rtl:ml-1"></i>Basic know how of Agile process and practices</li>
                    <li class="text-slate-400 mt-2"><i class="uil uil-arrow-right text-emerald-600 ltr:mr-1 rtl:ml-1"></i>Good understanding of object-oriented programming.</li>
                    <li class="text-slate-400 mt-2"><i class="uil uil-arrow-right text-emerald-600 ltr:mr-1 rtl:ml-1"></i>Good understanding of concurrent programming.</li>
                    <li class="text-slate-400 mt-2"><i class="uil uil-arrow-right text-emerald-600 ltr:mr-1 rtl:ml-1"></i>Sound knowledge of application architecture and design.</li>
                    <li class="text-slate-400 mt-2"><i class="uil uil-arrow-right text-emerald-600 ltr:mr-1 rtl:ml-1"></i>Excellent problem solving and analytical skills</li>
                </ul> -->

                <div class="mt-5">
                    <a href="{{ url_for('website_blueprint.jobApply',event_id=eventInfo.id) }}" class="btn rounded-md bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white ltr:md:ml-2 rtl:md:mr-2 w-full md:w-auto">Apply Now</a>
                </div>
            </div><!--end col-->

            <div class="lg:col-span-4 md:col-span-6">
                <div class="shadow dark:shadow-gray-700 rounded-md bg-white dark:bg-slate-900 sticky top-20">
                    <div class="p-6">
                        <h5 class="text-lg font-semibold">Job Information</h5>
                    </div>
                    <div class="p-6 border-t border-slate-100 dark:border-t-gray-700">
                        <ul class="list-none">
                            <li class="flex items-center">
                                <i data-feather="user-check" class="h-5 w-5"></i>

                                <div class="ltr:ml-4 rtl:mr-4">
                                    <p class="font-medium">Employee Type:</p>
                                    <span class="text-emerald-600 font-medium text-sm">{{eventInfo.emptype}}</span>
                                </div>
                            </li>

                            <li class="flex items-center mt-3">
                                <i data-feather="map-pin" class="h-5 w-5"></i>

                                <div class="ltr:ml-4 rtl:mr-4">
                                    <p class="font-medium">Location:</p>
                                    <span class="text-emerald-600 font-medium text-sm">{{eventInfo.location}}</span>
                                </div>
                            </li>

                            <li class="flex items-center mt-3">
                                <i data-feather="monitor" class="h-5 w-5"></i>

                                <div class="ltr:ml-4 rtl:mr-4">
                                    <p class="font-medium">Job Type:</p>
                                    <span class="text-emerald-600 font-medium text-sm">{{eventInfo.title}}</span>
                                </div>
                            </li>

                            <li class="flex items-center mt-3">
                                <i data-feather="briefcase" class="h-5 w-5"></i>

                                <div class="ltr:ml-4 rtl:mr-4">
                                    <p class="font-medium">Experience:</p>
                                    <span class="text-emerald-600 font-medium text-sm">{{eventInfo.experience}}</span>
                                </div>
                            </li>

                            <li class="flex items-center mt-3">
                                <i data-feather="book" class="h-5 w-5"></i>

                                <div class="ltr:ml-4 rtl:mr-4">
                                    <p class="font-medium">Qualifications:</p>
                                    <span class="text-emerald-600 font-medium text-sm">{{eventInfo.qualification}}</span>
                                </div>
                            </li>

            

                            <li class="flex items-center mt-3">
                                <i data-feather="clock" class="h-5 w-5"></i>

                                <div class="ltr:ml-4 rtl:mr-4">
                                    <p class="font-medium">Date posted:</p>
                                    <span class="text-emerald-600 font-medium text-sm">{{eventInfo.created_at}}</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div><!--end col-->
        </div><!--end grid-->
    </div><!--end container-->
</section>
{% endblock content %}

templates/website/views/user-application.html
{% extends "website/layouts/base.html" %}
{% block content %}
<section class="relative table w-full py-36 bg-[url('../../assets/images/hero/bg.jpg')] bg-top bg-no-repeat bg-cover ">
  <div class="absolute inset-0 bg-emerald-900/90"></div>
  <div class="container">
    <div class="grid grid-cols-1 text-center mt-10">
      <h3 class="md:text-3xl text-2xl md:leading-snug tracking-wide leading-snug font-medium text-white">User
        Application</h3>

    </div><!--end grid-->
  </div><!--end container-->

</section><!--end section-->
<section class="relative table w-full py-28 px-20 text-center">

  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="px-6 py-3">
            Job Id
          </th>
          <th scope="col" class="px-6 py-3">
            Title
          </th>
          <th scope="col" class="px-6 py-3">
            Description
          </th>
          <th scope="col" class="px-6 py-3">
            Status
          </th>
          <th scope="col" class="px-6 py-3">
            Applicant Status
          </th>
          <th scope="col" class="px-6 py-3">
            Empolyee Type
          </th>
          <th scope="col" class="px-6 py-3">
            Job Creation
          </th>
          <th scope="col" class="px-6 py-3">
            Reviews
          </th>
          <th scope="col" class="px-6 py-3">
            Chat with Organization
          </th>
        </tr>
      </thead>
      <tbody>
        {% for record in data %}
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
          <td class="px-6 py-4">{{record.id}}</td>
          <td class="px-6 py-4">{{record.title}}</td>
          <td class="px-6 py-4">{{record.description}}</td>
          <td class="px-6 py-4">{{record.status}}</td>
          <td class="px-6 py-4">{{record.applicantStatus}}</td>
          <td class="px-6 py-4">{{record.emptype}}</td>
          <td class="px-6 py-4">{{record.created_at}}</td>
          <td class="px-6 py-4">
            {% if record.applicantStatus == 'pending' %}
            Waiting for Approval/Rejection
            {% elif record.review %}
             {{record.review}}
             {% else %}
             <a href="{{url_for('website_blueprint.userReview',event_id=record.id)}}"
              class="btn bg-emerald-600 hover:bg-emerald-700 border-emerald-600 hover:border-emerald-700 text-white mt-2 rounded-md"><i
                class="uil uil-envelope"></i> Give Review</a>
            {% endif%}
          </td>
          <td class="px-6 py-4">
            <button class="btn btn-link btn-icon mr-1 p-0 b-0">
              <a href="{{url_for('website_blueprint.chat',receiver_id=record.organization_id)}}">
                <i class="fas fa-comment"></i>
              </a>
            </button>
          </td>

        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

</section>

{% endblock content %}